name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure Docker to Authenticate to GCR
        uses: ./
        with:
          service-account-key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
